### ISSUE TITLE
Can't find meta.json and calibration file

### ISSUE THREAD

**Issue by steward1212** [lmb-freiburg/contra-hand#2]
Impressive work.

I would like to use your whole dataset. However, I can't find meta.json and calibration file for whole dataset. I do see those in tester. Can you offer the files? Thanks.

**Comment by zimmerm** [comment]
Welcome to our first customer :-) 

We have simply forgotten to link the respective file on the [dataset page](https://lmb.informatik.uni-freiburg.de/resources/datasets/HanCo.en.html). Look for 'HanCo Camera Calibration and Meta Information'. In case you don't see it you maybe need to refresh the page because of the browser cache. The meta file of the tester is actually complete and identical to the one that is contained in the link.
